const express = require("express")
const connect = require("./config/db")
const userrouter = require("./routes/user.route")
const app = express()
app.use(express.urlencoded({extended : true}))
const cookie = require("cookie-parser")
const taskroute = require("./routes/task.route")
require("dotenv").config()
app.use(express.json())
app.set("view engine" , "ejs")
app.set("views" , __dirname + "/view")
app.use(cookie())
app.use("/user" , userrouter)
app.use("/task" , taskroute)
app.listen(process.env.PORT,()=>{
    connect()
    console.log(`port is start ${process.env.PORT}`)
})